#!/bin/bash

# Check if the script is running as root
if [ "$EUID" -eq 0 ]; then
    echo "Please run this script as a regular user, not as root."
    exit 1
fi

if [ ! -d "/home/${USER}/GNUstep" ] ; then
  mkdir /home/${USER}/GNUstep/
  cp -R /etc/GNUstep/* /home/${USER}/GNUstep/
fi

xhost +

docker run -it --rm \
    -e DISPLAY=$DISPLAY \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -v /home/$USER:/home/$USER \
    -v /etc/passwd:/etc/passwd:ro \
    -v /etc/group:/etc/group:ro \
    --user $(id -u):$(id -g) \
    ghcr.io/pkgdemon/dockerstep:main