#!/bin/bash

# Check if the script is running as root
if [ "$EUID" -eq 0 ]; then
    echo "Please run this script as a regular user, not as root."
    exit 1
fi

xhost +

docker run -it --rm \
    -e DISPLAY=$DISPLAY \
    -e USER=$USER \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -v /home/$USER:/home/$USER \
    -v /etc/passwd:/etc/passwd:ro \
    -v /etc/group:/etc/group:ro \
    -v /etc/shadow:/etc/shadow:ro \
    -v /etc/sudoers.d:/etc/sudoers.d:ro \
    --user $(id -u):$(id -g) \
    ghcr.io/pkgdemon/dockerstep:main